const EDIT_PREFIX='sage.edit.';
const EDITABLE_SELECTOR='main h1, main h2, main h3, main p, main .chip, main .tag, main .hint, main .sub, main .desc, main .task-title, main .task-meta, main .task-note, main .date-pill, main .stat, main a.card h2, main a.card p, main .link-card, main strong';
let editEnabled=false;
function pathKey(){return location.pathname.split('/').pop()||'index.html'}
function editableKey(el,index){return EDIT_PREFIX+pathKey()+'.'+index}
function getEditables(){return Array.from(document.querySelectorAll(EDITABLE_SELECTOR)).filter(el=>!el.closest('.nav')&&!el.closest('.mobile')&&!el.closest('.edit-dock')&&!el.closest('script')&&!el.closest('form')&&!el.closest('button'))}
function loadEdits(){getEditables().forEach((el,index)=>{el.dataset.editable='true';el.dataset.editKey=editableKey(el,index);const saved=localStorage.getItem(el.dataset.editKey);if(saved!==null){el.innerHTML=saved}if(!el.textContent.trim())el.classList.add('editable-empty')})}
function setEditing(on){editEnabled=on;document.body.classList.toggle('editing',on);getEditables().forEach(el=>{el.contentEditable=on?'true':'false';el.spellcheck=false});toast(on?'编辑模式已开启：直接点文字修改':'编辑模式已关闭')}
function saveEdits(){getEditables().forEach(el=>{localStorage.setItem(el.dataset.editKey,el.innerHTML);el.classList.toggle('editable-empty',!el.textContent.trim())});toast('已保存到这个浏览器')}
function resetPageEdits(){if(!confirm('确定清空本页手动编辑吗？任务/进度记录不会被清空。'))return;getEditables().forEach(el=>localStorage.removeItem(el.dataset.editKey));location.reload()}
function exportEdits(){const data={version:1,createdAt:new Date().toISOString(),items:{}};for(let i=0;i<localStorage.length;i++){const key=localStorage.key(i);if(key&&key.startsWith('sage.'))data.items[key]=localStorage.getItem(key)}const blob=new Blob([JSON.stringify(data,null,2)],{type:'application/json'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download='sage-utopia-backup.json';a.click();URL.revokeObjectURL(url);toast('已导出备份')}
function importEdits(file){const reader=new FileReader();reader.onload=()=>{try{const data=JSON.parse(reader.result);Object.entries(data.items||{}).forEach(([key,value])=>{if(key.startsWith('sage.'))localStorage.setItem(key,value)});toast('已导入备份，页面即将刷新');setTimeout(()=>location.reload(),700)}catch(e){toast('导入失败，请确认是 Sage Utopia 备份文件')}};reader.readAsText(file)}
function toast(text){let el=document.querySelector('.edit-toast');if(!el){el=document.createElement('div');el.className='edit-toast';document.body.appendChild(el)}el.textContent=text;el.classList.add('show');clearTimeout(window.__editToastTimer);window.__editToastTimer=setTimeout(()=>el.classList.remove('show'),1800)}
function addEditDock(){const dock=document.createElement('div');dock.className='edit-dock';dock.innerHTML='<button type="button" id="editToggle">编辑</button><button type="button" class="quiet" id="editSave">保存</button><button type="button" class="quiet" id="editReset">重置本页</button><button type="button" class="quiet" id="editExport">导出备份</button><label class="quiet">导入备份<input type="file" id="editImport" accept="application/json"></label>';document.body.appendChild(dock);document.getElementById('editToggle').addEventListener('click',()=>{setEditing(!editEnabled);document.getElementById('editToggle').textContent=editEnabled?'退出编辑':'编辑'});document.getElementById('editSave').addEventListener('click',saveEdits);document.getElementById('editReset').addEventListener('click',resetPageEdits);document.getElementById('editExport').addEventListener('click',exportEdits);document.getElementById('editImport').addEventListener('change',e=>{const file=e.target.files&&e.target.files[0];if(file)importEdits(file)})}
document.addEventListener('input',e=>{const el=e.target;if(el&&el.dataset&&el.dataset.editKey)localStorage.setItem(el.dataset.editKey,el.innerHTML)});
loadEdits();addEditDock();