(function(){
  function loadCss(href,key){const old=document.querySelector(`link[data-${key}]`);if(old){old.href=href;return}const l=document.createElement('link');l.rel='stylesheet';l.href=href;l.dataset[key]='true';document.head.appendChild(l)}
  function loadScript(src,key){if(document.querySelector(`script[data-${key}]`))return;const s=document.createElement('script');s.src=src;s.dataset[key]='true';document.body.appendChild(s)}
  function loadHelpers(){loadCss('theme-refresh.css?v=8','sageTheme');loadScript('sage-ui.js?v=1','sageUI');loadScript('brand-edit-fix.js?v=2','brandEditFix')}
  loadHelpers();
  const PAGES={
    home:{file:'index.html',label:'首页',branches:[['#homeGuestbook','留言板'],['#taskBoard','操作区']]},
    study:{file:'study.html',label:'学习中心',branches:[['#planner','课程'],['#assignments','作业'],['#links','官方链接'],['#sync','同步']]},
    career:{file:'career.html',label:'求职中心',branches:[['#careerOverview','概览'],['#careerFormSection','新增机会'],['#careerListSection','求职列表']]},
    finance:{file:'finance.html',label:'财务中心',branches:[['main .grid.three','概览'],['#expenseFormSection','记支出'],['#expenseListSection','支出列表']]},
    growth:{file:'growth.html',label:'成长记录',branches:[['main .grid.three','概览'],['main .section','时间轴']]},
    friends:{file:'friends.html',label:'留言板',branches:[['#guestbook','留言板']]},
    resume:{file:'resume.html',label:'关于 Sage',branches:[['#resume-about','关于'],['#resume-portfolio','作品集'],['#resume-contact','联系'],['#data-management','数据']]},
    about:{file:'about.html',label:'关于 Sage',branches:[['#resume-about','关于'],['#resume-portfolio','作品集'],['#resume-contact','联系']]},
  };
  const primary=['home','study','career','finance','growth','friends','resume'];let loading=false;
  let shellInited=false;
  let openPageId=0;
  function keyFromPath(){let f=location.pathname.split('/').pop()||'index.html';return Object.keys(PAGES).find(k=>PAGES[k].file===f)||'home'}
  function keyFromHash(){let h=(location.hash||'').replace('#','');return PAGES[h]?h:null}
  function currentKey(){return keyFromPath()}
  function primaryHtml(active){return primary.map(k=>`<a class="${active===k?'active':''}" href="${PAGES[k].file}" data-page="${k}">${PAGES[k].label}</a>`).join('')}
  function branchHref(active,selector){return PAGES[active].file+(String(selector).startsWith('#')?selector:'')}
  function branchHtml(active){let cfg=PAGES[active]||PAGES.home;return cfg.branches.map((b,i)=>`<a href="${branchHref(active,b[0])}" data-branch="${i}">${b[1]}</a>`).join('')}
  function updateMobileNavOffset(){const mobile=document.querySelector('.mobile');if(!mobile)return;document.documentElement.style.setProperty('--sage-mobile-nav-height',`${Math.ceil(mobile.getBoundingClientRect().height+32)}px`)}
  function updateNavActive(active){document.querySelectorAll('.mobile-scroll a[data-page],.side .nav a[data-page]').forEach(a=>{a.classList.toggle('active',a.dataset.page===active)});document.querySelectorAll('.mobile-branches').forEach(el=>{el.innerHTML=branchHtml(active)});document.querySelectorAll('.side .nav .section-index').forEach(el=>{el.innerHTML='<p>本页分支</p>'+branchHtml(active)});updateMobileNavOffset();bindNav()}
  function ensureMobileNav(){if(!document.querySelector('.mobile')){const m=document.createElement('div');m.className='mobile';const brand=document.querySelector('.side .brand');m.innerHTML=`<a class="brand" href="index.html">${brand?brand.innerHTML:'<span class="leaf"></span><span>Sage Utopia<span class="tag">柔软有序的成长小屋</span></span>'}</a><div class="mobile-scroll"></div>`;const shell=document.querySelector('.shell');if(shell)shell.insertAdjacentElement('beforebegin',m)}if(!document.querySelector('.mobile-branches')){const ms=document.querySelector('.mobile-scroll');if(ms){const b=document.createElement('div');b.className='mobile-branches';ms.insertAdjacentElement('afterend',b)}}}
  function normalizeShell(){if(!shellInited){shellInited=true;loadHelpers();ensureMobileNav()}const active=currentKey();document.querySelectorAll('.mobile-scroll').forEach(el=>{el.innerHTML=primaryHtml(active)});document.querySelectorAll('.mobile-more').forEach(el=>el.remove());if(!document.querySelector('.mobile-branches')){const ms=document.querySelector('.mobile-scroll');if(ms){const b=document.createElement('div');b.className='mobile-branches';ms.insertAdjacentElement('afterend',b)}}document.querySelectorAll('.mobile-branches').forEach(el=>{el.innerHTML=branchHtml(active)});document.querySelectorAll('.side .nav').forEach(nav=>{nav.innerHTML=primaryHtml(active)+'<div class="section-index"><p>本页分支</p>'+branchHtml(active)+'</div>'});updateMobileNavOffset();bindNav()}
  function keepNavStill(){const nodes=Array.from(document.querySelectorAll('.side,.mobile-scroll,.mobile-branches'));const pos=nodes.map(el=>[el,el.scrollTop,el.scrollLeft]);return()=>pos.forEach(([el,top,left])=>{el.scrollTop=top;el.scrollLeft=left})}
  function ensureScrollTail(){let tail=document.getElementById('sage-scroll-tail');if(!tail){tail=document.createElement('div');tail.id='sage-scroll-tail';tail.setAttribute('aria-hidden','true');tail.style.cssText='height:520px;pointer-events:none;';document.body.appendChild(tail)}}
  function branchTopOffset(){const mobile=document.querySelector('.mobile');if(mobile&&getComputedStyle(mobile).display!=='none')return Math.ceil(mobile.getBoundingClientRect().height+16);return 64}
  function settleBranchPosition(target){const top=branchTopOffset();const rect=target.getBoundingClientRect();window.scrollTo({top:Math.max(0,window.scrollY+rect.top-top),behavior:'auto'})}
  function scrollToBranch(selector,replaceUrl){const target=document.querySelector(selector);if(!target)return false;ensureScrollTail();const restoreNav=keepNavStill();if(document.activeElement&&document.activeElement.blur)document.activeElement.blur();settleBranchPosition(target);restoreNav();if(replaceUrl)history.replaceState(history.state||{},'',replaceUrl);requestAnimationFrame(()=>{settleBranchPosition(target);restoreNav()});setTimeout(()=>{settleBranchPosition(target);restoreNav()},80);return true}
  function branchFromLink(a){if(!a)return null;const href=a.getAttribute('href')||'';if(a.dataset.branch!=null){const cfg=PAGES[currentKey()]||PAGES.home;const b=cfg.branches[Number(a.dataset.branch)];return b&&String(b[0]).startsWith('#')?{selector:b[0],url:PAGES[currentKey()].file+b[0]}:null}if(!a.closest('.section-index,.mobile-branches'))return null;try{const u=new URL(href,location.href);const currentFile=location.pathname.split('/').pop()||'index.html';if((u.pathname.split('/').pop()||'index.html')!==currentFile||!u.hash)return null;return{selector:u.hash,url:(PAGES[currentKey()]||PAGES.home).file+u.hash}}catch{return null}}
  function runScripts(doc){Array.from(doc.body.querySelectorAll('script')).forEach(old=>{const src=old.getAttribute('src')||'';if(src.includes('site-shell.js')||src.includes('brand-edit-fix.js'))return;if(src.includes('edit-mode.js')&&window.__sageEditLoaded)return;if(src.includes('tasks.js')&&window.__sageTasksLoaded)return;if(src.includes('sage-cloud-data.js')&&window.SageCloudData)return;if(src.includes('sage-data.js')&&window.SageData)return;if(src.includes('career.js')&&window.__careerInited)return;if(src.includes('finance.js')&&window.__financeInited)return;if(src.includes('growth.js')&&window.__growthInited)return;if(src.includes('study.js')&&window.__studyInited)return;if(src.includes('resume.js')&&window.__resumeInited)return;if(src.includes('portfolio.js')&&window.__portfolioInited)return;if(src.includes('sage-cloud-sync.js')&&window.__sageCloudSyncInited)return;if(src.includes('cloud-sync.js')&&window.__cloudSyncInited)return;if(src.includes('sage-sync.js')&&window.__sageSyncLoaded)return;const s=document.createElement('script');if(src){s.src=src;if(old.type)s.type=old.type;if(src.includes('edit-mode.js'))window.__sageEditLoaded=true;if(src.includes('tasks.js')){window.__sageTasksLoaded=true;s.onload=function(){rebindTasksForm()};s.dataset.sageModule='tasks'}if(src.includes('career.js'))window.__careerInited=true;if(src.includes('finance.js'))window.__financeInited=true;if(src.includes('growth.js'))window.__growthInited=true;if(src.includes('sage-cloud-sync.js'))window.__sageCloudSyncInited=true;/* module flags set by modules themselves after init */}else{s.textContent='(()=>{\n'+old.textContent+'\n})();'}document.body.appendChild(s)})}
  function rebindTasksForm(){const form=document.getElementById('itemForm');if(form&&window.SageTasks){form.onsubmit=null;form.removeEventListener('submit',window.__sageAddItem);form.addEventListener('submit',window.__sageAddItem=window.SageTasks.addItem)}if(window.SageTasks&&typeof window.SageTasks.loadItems==='function'){window.SageTasks.loadItems();window.SageTasks.renderItems();window.SageTasks.bindTaskContainer()}}
  function showNetworkFallback(){if(window.SageUI&&window.SageUI.toast){window.SageUI.toast('网络不稳定，正在重新打开页面。');return}const el=document.createElement('div');el.className='edit-toast show';el.textContent='网络不稳定，正在重新打开页面。';document.body.appendChild(el);setTimeout(()=>el.remove(),1600)}
  function hardOpen(key){if(!PAGES[key])return;showNetworkFallback();setTimeout(()=>{location.href=PAGES[key].file},220)}
  async function openPage(key,push){push=push!==false;if(!PAGES[key])return;var reqId=++openPageId;if(loading)return;loading=true;try{const res=await fetch(PAGES[key].file+'?spa='+Date.now());if(!res.ok)throw new Error('page fetch failed: '+res.status);if(reqId!==openPageId)return;const html=await res.text();if(reqId!==openPageId)return;const doc=new DOMParser().parseFromString(html,'text/html');const newMain=doc.querySelector('main');if(!newMain){hardOpen(key);return}const oldMain=document.querySelector('main');if(oldMain)oldMain.replaceWith(newMain);document.querySelectorAll('.sage-panel,.sage-entry,.toast').forEach(el=>el.remove());Array.from(doc.body.children).filter(el=>el.matches('.sage-panel,.sage-entry,.toast')).forEach(el=>document.body.appendChild(el.cloneNode(true)));document.title=doc.title||document.title;doc.querySelectorAll('head style').forEach(st=>{if(!st.textContent.includes('study-hero')||!document.getElementById('sage-study-style')){const copy=st.cloneNode(true);if(copy.textContent.includes('study-hero'))copy.id='sage-study-style';document.head.appendChild(copy)}});if(push)history.pushState({sagePage:key},'',PAGES[key].file);if(key==='study'){delete window.__studyInited;delete window.__sageSyncLoaded;}if(key==='career')delete window.__careerInited;if(key==='growth')delete window.__growthInited;if(key==='resume'){delete window.__resumeInited;delete window.__cloudSyncInited;delete window.__sageCloudSyncInited;}runScripts(doc);requestAnimationFrame(()=>{requestAnimationFrame(()=>{if(reqId!==openPageId)return;updateNavActive(key);if(window.initSageEditMode)window.initSageEditMode();if(window.__sageStudyRefresh)window.__sageStudyRefresh();if(window.__sageResumeRefresh)window.__sageResumeRefresh();window.scrollTo({top:0,behavior:'smooth'})})})}catch(err){console.warn('[sage-shell] 页面切换失败，改用完整跳转。',err);if(reqId===openPageId)hardOpen(key)}finally{loading=false}}
  function bindNav(){document.querySelectorAll('a[data-page]').forEach(a=>{a.onclick=e=>{e.preventDefault();openPage(a.dataset.page,true)}});document.querySelectorAll('a[data-branch]').forEach(a=>{a.onclick=e=>{const branch=branchFromLink(a);if(!branch)return;e.preventDefault();scrollToBranch(branch.selector,branch.url)}})}
  window.addEventListener('popstate',()=>openPage(currentKey(),false));
  window.addEventListener('hashchange',()=>{if(location.hash&&!PAGES[location.hash.replace('#','')])setTimeout(()=>scrollToBranch(location.hash,null),0)});
  document.addEventListener('click',function(e){const a=e.target.closest&&e.target.closest('a');const branch=branchFromLink(a);if(!branch)return;e.preventDefault();e.stopPropagation();scrollToBranch(branch.selector,branch.url)},true);
  window.__sageEditLoaded=!!document.querySelector('script[src*="edit-mode.js"]');window.__sageTasksLoaded=!!document.querySelector('script[src*="tasks.js"]');window.__careerInited=!!document.querySelector('script[src*="career.js"]');window.__financeInited=!!document.querySelector('script[src*="finance.js"]');window.__growthInited=!!document.querySelector('script[src*="growth.js"]');window.__studyInited=!!document.querySelector('script[src*="study.js"]');window.__resumeInited=!!document.querySelector('script[src*="resume.js"]');window.__portfolioInited=!!document.querySelector('script[src*="portfolio.js"]');window.__cloudSyncInited=!!document.querySelector('script[src*="cloud-sync.js"]');window.__sageCloudSyncInited=!!document.querySelector('script[src*="sage-cloud-sync.js"]');
  function ensureShell(){if(shellInited)return;const h=keyFromHash();if(h&&h!==keyFromPath()){history.replaceState({sagePage:h},'',PAGES[h].file);openPage(h,false);return}normalizeShell();if(location.hash&&!PAGES[location.hash.replace('#','')])requestAnimationFrame(()=>scrollToBranch(location.hash,null))}
  document.addEventListener('DOMContentLoaded',ensureShell);
  window.addEventListener('resize',updateMobileNavOffset);
  window.addEventListener('load',updateMobileNavOffset);
  if(window.ResizeObserver){const watchMobile=()=>{const mobile=document.querySelector('.mobile');if(mobile&&!mobile.__sageResizeObserver){mobile.__sageResizeObserver=new ResizeObserver(updateMobileNavOffset);mobile.__sageResizeObserver.observe(mobile);updateMobileNavOffset()}};document.addEventListener('DOMContentLoaded',watchMobile);setTimeout(watchMobile,80);setTimeout(watchMobile,500)}
  if(document.readyState!=='loading')ensureShell();
})();
