(function(){
  function loadCss(href,key){const old=document.querySelector(`link[data-${key}]`);if(old){old.href=href;return}const l=document.createElement('link');l.rel='stylesheet';l.href=href;l.dataset[key]='true';document.head.appendChild(l)}
  function loadScript(src,key){if(document.querySelector(`script[data-${key}]`))return;const s=document.createElement('script');s.src=src;s.dataset[key]='true';document.body.appendChild(s)}
  function loadHelpers(){loadCss('theme-refresh.css?v=3','sageTheme');loadScript('brand-edit-fix.js?v=2','brandEditFix')}
  loadHelpers();
  const PAGES={
    home:{file:'index.html',label:'首页',branches:[['#quickAdd','快速新增'],['#taskBoard','操作区']]},
    study:{file:'study.html',label:'学习中心',branches:[['#planner','换课'],['#links','官方链接'],['#visa','485'],['#sync-study','同步']]},
    career:{file:'career.html',label:'求职中心',branches:[['main .grid.three','概览'],['main .section','求职列表']]},
    growth:{file:'growth.html',label:'成长记录',branches:[['main .grid.three','概览'],['main .section','时间轴']]},
    resume:{file:'resume.html',label:'关于 Sage',branches:[['main .hero','摘要'],['#resume-about','关于'],['#resume-contact','联系'],['#resume-portfolio','作品'],['#resume-skills','技能']]}
  };
  const primary=['home','study','career','growth','resume'];let loading=false;
  function keyFromPath(){let f=location.pathname.split('/').pop()||'index.html';return Object.keys(PAGES).find(k=>PAGES[k].file===f)||'home'}
  function keyFromHash(){let h=(location.hash||'').replace('#','');return PAGES[h]?h:null}
  function currentKey(){return keyFromHash()||keyFromPath()}
  function primaryHtml(active){return primary.map(k=>`<a class="${active===k?'active':''}" href="index.html#${k}" data-page="${k}">${PAGES[k].label}</a>`).join('')}
  function branchHtml(active){let cfg=PAGES[active]||PAGES.home;return cfg.branches.map((b,i)=>`<a href="${String(b[0]).startsWith('#')?b[0]:'#'}" data-branch="${i}">${b[1]}</a>`).join('')}
  function normalizeShell(){loadHelpers();const active=currentKey();document.querySelectorAll('.mobile-scroll').forEach(el=>{el.innerHTML=primaryHtml(active)});document.querySelectorAll('.mobile-more').forEach(el=>el.remove());if(!document.querySelector('.mobile-branches')){const ms=document.querySelector('.mobile-scroll');if(ms){const b=document.createElement('div');b.className='mobile-branches';ms.insertAdjacentElement('afterend',b)}}document.querySelectorAll('.mobile-branches').forEach(el=>{el.innerHTML=branchHtml(active)});document.querySelectorAll('.side .nav').forEach(nav=>{nav.innerHTML=primary.map(k=>`<a class="${active===k?'active':''}" href="index.html#${k}" data-page="${k}">${PAGES[k].label}</a>`).join('')+'<div class="section-index"><p>本页分支</p>'+branchHtml(active)+'</div>'});bindNav()}
  function runScripts(doc){Array.from(doc.body.querySelectorAll('script')).forEach(old=>{const src=old.getAttribute('src')||'';if(src.includes('site-shell.js')||src.includes('brand-edit-fix.js'))return;if(src.includes('edit-mode.js')&&window.__sageEditLoaded)return;if(src.includes('tasks.js')&&window.__sageTasksLoaded)return;const s=document.createElement('script');if(src){s.src=src;if(src.includes('edit-mode.js'))window.__sageEditLoaded=true;if(src.includes('tasks.js'))window.__sageTasksLoaded=true}else{s.textContent='(()=>{\n'+old.textContent+'\n})();'}document.body.appendChild(s)})}
  async function openPage(key,push=true){if(loading||!PAGES[key])return;loading=true;try{const res=await fetch(PAGES[key].file+'?spa='+Date.now());const html=await res.text();const doc=new DOMParser().parseFromString(html,'text/html');const newMain=doc.querySelector('main');if(!newMain){location.href=PAGES[key].file;return}const oldMain=document.querySelector('main');if(oldMain)oldMain.replaceWith(newMain);document.querySelectorAll('.sage-panel,.sage-entry,.toast').forEach(el=>el.remove());Array.from(doc.body.children).filter(el=>el.matches('.sage-panel,.sage-entry,.toast')).forEach(el=>document.body.appendChild(el.cloneNode(true)));document.title=doc.title||document.title;doc.querySelectorAll('head style').forEach(st=>{if(!st.textContent.includes('study-hero')||!document.getElementById('sage-study-style')){const copy=st.cloneNode(true);if(copy.textContent.includes('study-hero'))copy.id='sage-study-style';document.head.appendChild(copy)}});if(push)history.pushState({sagePage:key},'',`index.html#${key}`);runScripts(doc);setTimeout(()=>{normalizeShell();if(window.initSageEditMode)window.initSageEditMode();window.scrollTo({top:0,behavior:'smooth'})},40)}finally{loading=false}}
  function bindNav(){document.querySelectorAll('a[data-page]').forEach(a=>{a.onclick=e=>{e.preventDefault();openPage(a.dataset.page,true)}});document.querySelectorAll('a[data-branch]').forEach(a=>{a.onclick=e=>{e.preventDefault();const cfg=PAGES[currentKey()]||PAGES.home;const b=cfg.branches[Number(a.dataset.branch)];const target=document.querySelector(b[0]);if(target)target.scrollIntoView({behavior:'smooth',block:'start'})}})}
  window.addEventListener('popstate',()=>openPage(currentKey(),false));
  window.__sageEditLoaded=!!document.querySelector('script[src*="edit-mode.js"]');window.__sageTasksLoaded=!!document.querySelector('script[src*="tasks.js"]');
  document.addEventListener('DOMContentLoaded',()=>{normalizeShell();const h=keyFromHash();if(h&&h!==keyFromPath())openPage(h,false)});
  if(document.readyState!=='loading'){normalizeShell();const h=keyFromHash();if(h&&h!==keyFromPath())openPage(h,false)}
})();
