const KEY='sage.progress.items.v2';
const OLD_KEY='sage.progress.items.v1';
const defaults=[
  {id:'progress-book',section:'progress',title:'读完一本传播学相关书',type:'阅读',start:'2026-06-05',due:'2026-07-05',total:320,current:48,unit:'页',done:false,note:'每天记录看到第几页。'},
  {id:'progress-portfolio',section:'progress',title:'整理作品集首页',type:'作品集',start:'2026-06-05',due:'2026-06-16',total:5,current:1,unit:'步',done:false,note:'封面、项目简介、负责内容、成果展示、联系方式。'},
  {id:'habit-reading',section:'habit',title:'每天阅读 20 分钟',type:'阅读习惯',start:'2026-06-05',due:'',total:30,current:3,unit:'天',done:false,note:'适合记录连续天数或本月完成次数。'},
  {id:'habit-portfolio',section:'habit',title:'每周更新一次作品集',type:'成长习惯',start:'2026-06-05',due:'',total:12,current:1,unit:'次',done:false,note:'每次只补充一个小地方也算。'},
  {id:'task-moodle',section:'task',title:'检查 Moodle 作业截止日期',type:'学习任务',start:'2026-06-05',due:'2026-06-08',total:1,current:0,unit:'项',done:false,note:'同步中心可以辅助整理。'}
];
let items=[];
const sectionMeta={progress:{title:'进度追踪',empty:'这里放长期目标，比如读完一本书、整理作品集、完成课程项目。'},habit:{title:'习惯养成',empty:'这里放每天或每周重复的小习惯，比如阅读、运动、复盘。'},task:{title:'任务清单',empty:'这里放一次性待办，比如提交作业、投递申请、整理文件。'}};
function todayISO(){return new Date().toISOString().slice(0,10)}
function num(v,fallback=0){const n=Number(v);return(v===''||v===null||v===undefined||!Number.isFinite(n))?fallback:n}
function clamp(n,min,max){return Math.max(min,Math.min(max,n))}
function pct(item){const total=Math.max(num(item.total,1),1);return Math.round(clamp(num(item.current,0)/total,0,1)*100)}
function normalize(item){return {...item,section:item.section||guessSection(item.type),total:Math.max(num(item.total,1),1),current:num(item.current,0),unit:item.unit||'项'}}
function guessSection(type){if(type&&String(type).includes('习惯'))return 'habit';if(['阅读','作品集','成长'].includes(type))return 'progress';return 'task'}
function loadItems(){try{items=JSON.parse(localStorage.getItem(KEY))||null;if(!items){const old=JSON.parse(localStorage.getItem(OLD_KEY)||'null');items=old?old.map(normalize):defaults}}catch(e){items=defaults}items=items.map(normalize);saveItems()}
function saveItems(){localStorage.setItem(KEY,JSON.stringify(items))}
function quickType(section,type){document.getElementById('itemSection').value=section;document.getElementById('itemType').value=type;document.getElementById('itemTitle').focus();document.getElementById('taskBoard').scrollIntoView({behavior:'smooth',block:'start'})}
function addItem(e){e.preventDefault();const title=document.getElementById('itemTitle').value.trim();if(!title)return;const total=Math.max(num(document.getElementById('itemTotal').value,1),1);const current=clamp(num(document.getElementById('itemCurrent').value,0),0,total);const section=document.getElementById('itemSection').value;items.unshift({id:'item-'+Date.now()+'-'+Math.random().toString(36).slice(2,8),section,title,type:document.getElementById('itemType').value.trim()||sectionMeta[section].title,start:document.getElementById('itemStart').value,due:document.getElementById('itemDue').value,total,current,unit:document.getElementById('itemUnit').value.trim()||defaultUnit(section),done:current>=total,note:document.getElementById('itemNote').value.trim()});document.getElementById('itemForm').reset();saveItems();renderItems();say('已收好啦。它已经放进对应分区，可以直接记录进度。')}
function defaultUnit(section){return section==='habit'?'天':section==='progress'?'步':'项'}
function updateProgress(id){const input=document.getElementById('progress-'+id);items=items.map(item=>{if(item.id!==id)return item;const total=Math.max(num(item.total,1),1);const current=clamp(num(input.value,item.current),0,total);return {...item,current,done:current>=total}});saveItems();renderItems();say('进度更新好了。慢慢推进也很厉害。')}
function completeItem(id){items=items.map(item=>item.id===id?{...item,_prevCurrent:item.current,current:Math.max(num(item.total,1),1),done:true}:item);saveItems();renderItems();say('完成啦，给今天的自己一点掌声。')}
function restoreItem(id){items=items.map(item=>item.id===id?{...item,done:false,current:item._prevCurrent!=null?item._prevCurrent:Math.min(num(item.current,0),Math.max(num(item.total,1)-1,0))}:item);items=items.map(item=>{if(item._prevCurrent!=null){const{_prevCurrent,...rest}=item;return rest}return item});saveItems();renderItems()}
function deleteItem(id){if(!confirm('确定删除这一项吗？'))return;items=items.filter(item=>item.id!==id);saveItems();renderItems()}
function say(text){let el=document.getElementById('sageMessage');if(!el){el=document.createElement('div');el.id='sageMessage';el.style.cssText='position:fixed;left:50%;bottom:24px;transform:translateX(-50%);background:#334139;color:#fff;border-radius:999px;padding:10px 16px;font-size:13px;font-weight:800;z-index:10000;opacity:0;pointer-events:none;transition:opacity .18s ease,transform .18s ease';document.body.appendChild(el)}el.textContent=text;el.style.opacity='1';el.style.transform='translateX(-50%) translateY(0)';clearTimeout(window.__sageMsgTimer);window.__sageMsgTimer=setTimeout(()=>{el.style.opacity='0';el.style.transform='translateX(-50%) translateY(8px)'},2000)}
function isDueSoon(item){if(item.done||!item.due)return false;const d=new Date(item.due+'T00:00:00');const now=new Date(todayISO()+'T00:00:00');const diff=(d-now)/86400000;return diff>=0&&diff<=7}
function itemCard(item){const percent=pct(item);const unit=item.unit||'项';return `<div class="task-row ${item.done?'done':''}"><div class="task-card-top"><div><div class="task-title">${escapeHTML(item.title)}</div><div class="task-meta">${escapeHTML(item.type)} · ${item.current}/${item.total} ${escapeHTML(unit)} · ${percent}%</div></div><span class="task-badge">${item.done?'已完成':percent>=70?'接近完成':'进行中'}</span></div><div class="progress-track"><span class="progress-fill" style="width:${percent}%"></span></div><div class="progress-line"><span>进度 ${percent}%</span><span>${item.current}/${item.total} ${escapeHTML(unit)}</span></div><div class="date-row">${item.start?`<span class="date-pill">开始 ${item.start}</span>`:''}${item.due?`<span class="date-pill">计划截止 ${item.due}</span>`:'<span class="date-pill">长期保持</span>'}</div>${item.note?`<div class="task-note">${escapeHTML(item.note)}</div>`:''}<div class="progress-update"><input class="field" id="progress-${item.id}" type="number" min="0" max="${item.total}" value="${item.current}" placeholder="更新当前进度"><button class="mini ghost" onclick="updateProgress('${item.id}')">记录</button></div><div class="task-actions"><button class="mini ghost" onclick="${item.done?`restoreItem('${item.id}')`:`completeItem('${item.id}')`}">${item.done?'恢复':'完成'}</button><button class="mini danger" onclick="deleteItem('${item.id}')">删除</button></div></div>`}
function fillSection(section){const list=items.filter(item=>item.section===section);const active=list.filter(item=>!item.done&&pct(item)<100);const done=list.filter(item=>item.done||pct(item)>=100);document.getElementById(section+'List').innerHTML=active.length?active.map(itemCard).join(''):`<div class="empty">${sectionMeta[section].empty}</div>`;document.getElementById(section+'Done').innerHTML=done.length?done.map(itemCard).join(''):'<div class="empty">完成后会出现在这里。</div>';document.getElementById(section+'Count').textContent=active.length;document.getElementById(section+'Avg').textContent=list.length?Math.round(list.reduce((s,item)=>s+pct(item),0)/list.length)+'%':'0%'}
function renderItems(){fillSection('progress');fillSection('habit');fillSection('task');const open=items.filter(item=>!item.done&&pct(item)<100).length;const soon=items.filter(isDueSoon).length;const average=items.length?Math.round(items.reduce((s,item)=>s+pct(item),0)/items.length):0;const done=items.filter(item=>item.done||pct(item)>=100).length;document.getElementById('openCount').textContent=open;document.getElementById('todayCount').textContent=soon;document.getElementById('weekCount').textContent=average+'%';document.getElementById('doneCount').textContent=done}
function escapeHTML(s){return String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
document.getElementById('itemForm').addEventListener('submit',addItem);loadItems();renderItems();